### ISSUE TITLE
VS Code Intellisense - Symfony Plugin

### ISSUE THREAD

**Issue by sotnf** [nystudio107/craft-autocomplete#13]
I see the ReadMe mentions that VSCode doesn't support "intellisense" plug-ins but I've seen a few that describe themselves that way. I was wondering if anyone has reviewed the current capabilities of VSCode to see if this plug-in could be adapted to be used by an existing plugin like "[Symfony for VSCode](https://github.com/TheNouillet/symfony-vscode)".

I searched the repo and didn't see any other mention of VSCode other than the readme file.

**Comment by khalwat** [comment]
It does not work with VS Code currently.
