### ISSUE TITLE
PHPStorm still not picking up hints despite a correct-looking setup

### ISSUE THREAD

**Issue by roberttolton** [nystudio107/craft-autocomplete#4]
### Question
I'm not sure what my PHPStorm install is getting wrong about my app, but it cannot resolve the hinted properties on the `craft` variable. I am using a Lando (Docker) local setup, and can confirm that PHPStorm has bound read/write access to the entire `storage` directory, including the `compiled_classes` directory.

### Additional context

`AutocompleteVariable.php`
![Screenshot 2021-08-23 at 13 01 03](https://user-images.githubusercontent.com/3510875/130444143-0b24dfcc-6a59-4f61-b57b-b9dc79afd9d1.png)

`craft` variable is correctly showing as an instance of the `AutocompleteVariable` class
![Screenshot 2021-08-23 at 13 00 13](https://user-images.githubusercontent.com/3510875/130444235-392d8d04-b863-42c3-89b4-32cc8c608620.png)

But I cannot auto-complete `imagerx`, as an example
![Screenshot 2021-08-23 at 13 01 32](https://user-images.githubusercontent.com/3510875/130444300-ed02e55a-368c-41cc-88e6-0fd7cac24b5f.png)

I have cleared Craft's caches and temp files and regenerated the auto-complete classes.
I have tried marking the `complied_classes` folder as a 'Source Root' in PHPStorm.
I have not configured the Symfony plugin for this project beyond the defaults - does it need configuring?
I have also tried clearing the Index in the Symfony plugin, invalidating all PHPStorm caches and rebooting.

**Comment by bencroker** [comment]
Is autocompletion working for `{{ craft.globals }}` or `{{ craft.blitz }}`?

**Comment by roberttolton** [comment]
@bencroker So.. it's working now, oddly.

The only thing I changed since my last post was unmarking `compiled_classes` as a 'Source Root', but I doubt that's anything to do with it (?).

As grateful as I am that it's now working, it's annoying I can't pinpoint what the fix was, as none of my steps outlined in the first post offered an immediate, re-testable resolution and I'm not sure what might cause it to resurface.

Anyhow, thanks for your time!

**Comment by khalwat** [comment]
If I had to guess, it'd be because the index wasn't completed yet

**Comment by roberttolton** [comment]
@khalwat I thought that, but I checked each time and waited for PHPStorm's background processes to finish before re-testing. But, yeah, it would seem that it just sorted itself out.

**Comment by jaydensmith** [comment]
My IDE isn't picking up hints if the files are .gitignore'd. If I add exceptions for the generated classes everything works...
```
!/storage/runtime/compiled_classes/AutocompleteVariable.php
!/storage/runtime/compiled_classes/AutocompleteTwigExtension.php
```

**Comment by khalwat** [comment]
That's pretty odd @jaydensmith -- I have them `.gitignored` without incident.

**Comment by bencroker** [comment]
Sounds like it might be an IDE configuration setting?
