### ISSUE TITLE
Uninstalling a plugin can cause an exception

### ISSUE THREAD

**Issue by khalwat** [nystudio107/craft-autocomplete#5]
Uninstalling a plugin can cause Autocomplete to kick in and attempt to regenerate its files. Problem is, the Twig context will contain references to the stale globals.

Instead, on plugin uninstall, we should just invalidate the caches and let them regenerate on the next request.

Try uninstalling SEOmatic with Craft Autocomplete installed, and you'll see this bug.

**Comment by bencroker** [comment]
Good catch, fixed in https://github.com/nystudio107/craft-autocomplete/commit/9b6f0f3fb07da29b0e6c3a0bfa19affb6d11d40e. Feel free to tag a release if you're happy with it.

**Comment by khalwat** [comment]
Looks perfect, thx
