### ISSUE TITLE
No autocomplete for craft.commerce

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/craft-autocomplete#6]
There's no auto complete for `craft.commerce` like if you want to do: `craft.commerce.customers.getCustomerByUserId(currentUser.id)`

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-autocomplete/commit/1a62a9266a2f281cd5b3d3be23fc016ac81ed92e

Released as Craft Autocomplete 1.0.4 -> https://github.com/nystudio107/craft-autocomplete/releases/tag/1.0.4
